'use strict';var ajax_running=0,ajax_error=!1;ajax=function(b,c,g){var f={},h=[];if("undefined"!==typeof XMLHttpRequest){var f=new XMLHttpRequest,a;for(a in c)h.push(encodeURIComponent(a)+"="+encodeURIComponent(c[a]));f.open("POST",b,!0);f.onreadystatechange=function(){4===f.readyState&&200===f.status?g(null,f.responseText):4===f.readyState&&200!==f.status&&g(!0)};f.onerror=function(){g(!0)};f.setRequestHeader("Content-type","application/x-www-form-urlencoded");f.send(h.join("&"))}else showError("Dingen zijn niet ondersteund... update je browser...")};
function processReservations(b,c,g){for(var f in b){var h=b[f],a=new Date(h.dayFrom),e=new Date(h.dayTo),l="reserved";h.bySV&&(l="bySV");var h=a.getDate(),k=e.getDate();if(a.getMonth()!==e.getMonth())if(e.getMonth()===c)for(h=1,a=a.getDate();31>=a;a++){var d=getId("prev."+a+"."+(c+1)+"-"+g);null!=d&&d.classList.add(l)}else if(a.getMonth()===c)for(k=31,a=1;a<=e.getDate();a++)d=getId("next."+a+"."+(c+1)+"-"+g),null!=d&&d.classList.add(l);else if(a.getMonth()!=c&&e.getMonth()!=c){h=1;k=31;for(a=a.getDate();31>=
a;a++)d=getId("prev."+a+"."+(c+1)+"-"+g),null!=d&&d.classList.add(l);for(a=1;a<=e.getDate();a++)d=getId("next."+a+"."+(c+1)+"-"+g),null!=d&&d.classList.add(l)}for(a=h;a<=k;a++)d=getId(a+"."+(c+1)+"-"+g),null!=d&&d.classList.add(l)}}
function getReservationsMonth(b,c){0<ajax_running?(ajax_error=!0,getId("msg-calendar").innerHTML="<p></p>",getId("error-calendar").innerHTML='<p><button id="error-msg" class="verhuur-error">U klikt te snel, klik hier om te verversen.</button></p>',getId("error-msg").onclick=function(){ajax_running=0;ajax_error=!1;getId("error-calendar").innerHTML="<p></p>";getReservationsMonth(b,c)}):(ajax_running+=1,!1===ajax_error&&(getId("msg-calendar").innerHTML='<p class="verhuur-status">Ophalen van de reserveringen.</p>'),
ajax("../php/ReserveringMonth.php",{m:b+1,y:c},function(g,f){var h=g;if(!g)try{!1===ajax_error&&(processReservations(JSON.parse(f),b,c),getId("msg-calendar").innerHTML='<p class="verhuur-status">Reserveringen opgehaald.</p>')}catch(a){console.warn("Er is iets mis gegaan met het ophalen van de reserveringen.",f),h=!0}h&&(getId("msg-calendar").innerHTML='<p class="verhuur-status">Er is iets mis gegaan met het ophalen van de reserveringen.</p>');--ajax_running}))}
var Cal=function(b){this.divId=b;this.DaysOfWeek="Zo Ma Di Wo Do Vr Za".split(" ");this.Months="januari februari maart april mei juni juli augustus september oktober november december".split(" ");b=new Date;this.currMonth=b.getMonth();this.currYear=b.getFullYear();this.currDay=b.getDate()};Cal.prototype.nextMonth=function(){11==this.currMonth?(this.currMonth=0,this.currYear+=1):this.currMonth+=1;this.showcurr()};
Cal.prototype.previousMonth=function(){0==this.currMonth?(this.currMonth=11,--this.currYear):--this.currMonth;this.showcurr()};Cal.prototype.showcurr=function(){this.showMonth(this.currYear,this.currMonth)};
Cal.prototype.showMonth=function(b,c){var g=(new Date(b,c,1)).getDay(),f=(new Date(b,c+1,0)).getDate(),h=0==c?(new Date(b-1,11,0)).getDate():(new Date(b,c,0)).getDate(),a;a="<table><thead><tr>"+('<td colspan="7">'+this.Months[c]+" "+b+"</td>");a+='</tr></thead><tr class="days">';for(var e=0;e<this.DaysOfWeek.length;e++)a+='<td class="days">'+this.DaysOfWeek[e]+"</td>";a+="</tr>";e=1;do{var l=(new Date(b,c,e)).getDay();if(0==l)a+="<tr>";else if(1==e){a+="<tr>";for(var k=h-g+1,d=0;d<g;d++)a+='<td class="not-current" id="prev.'+
k+"."+(this.currMonth+1)+"-"+this.currYear+'">'+k+"</td>",k++}d=new Date;k=d.getFullYear();d=d.getMonth();a=k==this.currYear&&d==this.currMonth&&e==this.currDay?a+('<td class="today" id="'+e+"."+(this.currMonth+1)+"-"+this.currYear+'">'+e+"</td>"):a+('<td class="normal" id="'+e+"."+(this.currMonth+1)+"-"+this.currYear+'">'+e+"</td>");if(6==l)a+="</tr>";else if(e==f)for(k=1,l;6>l;l++)a+='<td class="not-current" id="next.'+k+"."+(this.currMonth+1)+"-"+this.currYear+'">'+k+"</td>",k++;e++}while(e<=f);
a+="</table>";document.getElementById(this.divId).innerHTML=a};window.onload=function(){var b=new Cal("divCal");b.showcurr();getReservationsMonth(b.currMonth,b.currYear);getId("btnNext").onclick=function(){b.nextMonth();getReservationsMonth(b.currMonth,b.currYear)};getId("btnPrev").onclick=function(){b.previousMonth();getReservationsMonth(b.currMonth,b.currYear)}};function getId(b){return document.getElementById(b)};
