'use strict';ajax=function(b,f,g){var e={},h=[];if("undefined"!==typeof XMLHttpRequest){var e=new XMLHttpRequest,a;for(a in f)h.push(encodeURIComponent(a)+"="+encodeURIComponent(f[a]));e.open("POST",b,!0);e.onreadystatechange=function(){4===e.readyState&&200===e.status?g(null,e.responseText):4===e.readyState&&200!==e.status&&g(!0)};e.onerror=function(){g(!0)};e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.send(h.join("&"))}else showError("Dingen zijn niet ondersteund... update je browser...")};
function processReservations(b,f,g){for(var e in b){var h=b[e],a=new Date(h.dayFrom);g=new Date(h.dayTo);var d="reserved";h.bySV&&(d="bySV");var h=a.getDate(),k=g.getDate();if(a.getMonth()!==g.getMonth())if(g.getMonth()===f)for(h=1,a=a.getDate();31>=a;a++){var c=getId("prev"+a);null!=c&&c.classList.add(d)}else if(a.getMonth()===f)for(k=31,a=1;a<=g.getDate();a++)c=getId("next"+a),null!=c&&c.classList.add(d);else if(a.getMonth()!=f&&g.getMonth()!=f){h=1;k=31;for(a=a.getDate();31>=a;a++)c=getId("prev"+
a),null!=c&&c.classList.add(d);for(a=1;a<=g.getDate();a++)c=getId("next"+a),null!=c&&c.classList.add(d)}for(a=h;a<=k;a++)c=getId(a),null!=c&&c.classList.add(d)}}
function getReservationsMonth(b,f){getId("msg-calendar").innerHTML='<p class="verhuur-status">Ophalen van de reserveringen.</p>';ajax("../php/ReserveringMonth.php",{m:b+1,y:f},function(g,e){var h=g;if(!g)try{processReservations(JSON.parse(e),b,f),getId("msg-calendar").innerHTML='<p class="verhuur-status">Reserveringen opgehaald.</p>'}catch(a){console.warn("Er is iets mis gegaan met het ophalen van de reserveringen.",e),h=!0}h&&(getId("msg-calendar").innerHTML='<p class="verhuur-status">Er is iets mis gegaan met het ophalen van de reserveringen.</p>')})}
var Cal=function(b){this.divId=b;this.DaysOfWeek="Zo Ma Di Wo Do Vr Za".split(" ");this.Months="januari februari maart april mei juni juli augustus september oktober november december".split(" ");b=new Date;this.currMonth=b.getMonth();this.currYear=b.getFullYear();this.currDay=b.getDate()};Cal.prototype.nextMonth=function(){11==this.currMonth?(this.currMonth=0,this.currYear+=1):this.currMonth+=1;this.showcurr()};
Cal.prototype.previousMonth=function(){0==this.currMonth?(this.currMonth=11,--this.currYear):--this.currMonth;this.showcurr()};Cal.prototype.showcurr=function(){this.showMonth(this.currYear,this.currMonth)};
Cal.prototype.showMonth=function(b,f){var g=(new Date(b,f,1)).getDay(),e=(new Date(b,f+1,0)).getDate(),h=0==f?(new Date(b-1,11,0)).getDate():(new Date(b,f,0)).getDate(),a;a="<table><thead><tr>"+('<td colspan="7">'+this.Months[f]+" "+b+"</td>");a+='</tr></thead><tr class="days">';for(var d=0;d<this.DaysOfWeek.length;d++)a+='<td class="days">'+this.DaysOfWeek[d]+"</td>";a+="</tr>";d=1;do{var k=(new Date(b,f,d)).getDay();if(0==k)a+="<tr>";else if(1==d){a+="<tr>";for(var c=h-g+1,l=0;l<g;l++)a+='<td class="not-current" id="prev'+
c+'">'+c+"</td>",c++}l=new Date;c=l.getFullYear();l=l.getMonth();a=c==this.currYear&&l==this.currMonth&&d==this.currDay?a+('<td class="today" id="'+d+'">'+d+"</td>"):a+('<td class="normal" id="'+d+'">'+d+"</td>");if(6==k)a+="</tr>";else if(d==e)for(c=1,k;6>k;k++)a+='<td class="not-current" id="next'+c+'">'+c+"</td>",c++;d++}while(d<=e);a+="</table>";document.getElementById(this.divId).innerHTML=a};
window.onload=function(){var b=new Cal("divCal");b.showcurr();getReservationsMonth(b.currMonth,b.currYear);getId("btnNext").onclick=function(){b.nextMonth();getReservationsMonth(b.currMonth,b.currYear)};getId("btnPrev").onclick=function(){b.previousMonth();getReservationsMonth(b.currMonth,b.currYear)}};function getId(b){return document.getElementById(b)};
