function $I(a){return document.getElementById(a)}function $el(a){return document.createElement(a)}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function removeClass(a){var b=document.getElementsByClassName(a),c;if(0!==b.length)if(1===b.length)b[0].classList.remove(a);else if(1<b.length)for(c=0;c<b.length;c++)b[c].classList.remove(a)}
var ajax={x:function(){if("undefined"!==typeof XMLHttpRequest)return new XMLHttpRequest;for(var a=["MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0","Microsoft.XmlHttp"],b,c=0;c<a.length;c++)try{b=new ActiveXObject(a[c]);break}catch(f){}return b},send:function(a,b,c,f,e){var d=ajax.x();d.open(c,a,e);d.onreadystatechange=function(){3<d.readyState&&(200===d.status?b(d.responseText):showError("Er is iets mis gegaan. (Status: "+d.status+")"))};"POST"===c&&d.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");d.send(f)},get:function(a,b,c){var f=[],e;for(e in b)f.push(encodeURIComponent(e)+"="+encodeURIComponent(b[e]));ajax.send(a+"?"+f.join("&"),c,"GET",null,!0)},post:function(a,b,c,f){var e=[],d;for(d in b)e.push(encodeURIComponent(d)+"="+encodeURIComponent(b[d]));ajax.send(a,c,"POST",e.join("&"),f)}};
function onScrollEvt(){var a=navElem.getBoundingClientRect(),b=groupElem.getBoundingClientRect();if(!menuClick)var c=stafElem.getBoundingClientRect(),f=actiElem.getBoundingClientRect(),e=contElem.getBoundingClientRect(),d=huurElem.getBoundingClientRect();0>=a.top&&b.top<=a.height?navElem.classList.add("nav-sticky-top"):navElem.classList.remove("nav-sticky-top");0>=b.top?$I("landing-page").style.visibility="hidden":$I("landing-page").removeAttribute("style");menuClick||(removeClass("menu-active"),
a.height>=b.top&&a.height<b.bottom&&menu.children[0].classList.add("menu-active"),a.height>=c.top&&a.height<c.bottom&&menu.children[1].classList.add("menu-active"),a.height>=f.top&&a.height<f.bottom&&menu.children[2].classList.add("menu-active"),a.height>=e.top&&a.height<e.bottom&&menu.children[3].classList.add("menu-active"),a.height>=d.top&&a.height<d.bottom&&menu.children[4].classList.add("menu-active"));scrolling=!1}
function requestScroll(){scrolling||requestAnimFrame(onScrollEvt);scrolling=!0}function setScroll(a){window.scrollTo?window.scrollTo(0,a):window.pageYOffset?window.pageYOffset=a:document.documentElement.scrollTop?document.documentElement.scrollTop=a:document.body.scrollTop&&(document.body.scrollTop=a)}
function scrollUp(a){function b(){if(50>g){var a=g;f=-d[0]*(a/=50)*(a-2)+c;var a=f,b=d[1]-1,e=d[1]+1;d[2]?a=a>=b&&a<=e:(a*=-1,a=a>=e&&a<=b);a?(setScroll(d[1]),menuClick=!1):(requestAnimFrame(h),g++)}}a=$I(a).offsetTop;var c,f,e=$I("navigatie").clientHeight,d=[],g=0,h=function(){setScroll(f);b()};c=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop;c<a?(d[0]=a-e-c,d[1]=a-e,d[2]=!0):(d[0]=-1*(c-(a-e)),d[1]=-1*(a-e),d[2]=!1);b()}
function showError(a,b){var c="",c=$I("errorMsg")?$I("errorMsg"):document.createElement("div");c.className="error-message";c.id="errorMsg";c.innerHTML='<i class="fa fa-times-circle"></i> '+a;b?$I(b).appendChild(c):console.error(a)}function removeError(){if($I("errorMsg")){var a=$I("errorMsg");a.parentNode.removeChild(a)}}function showSuccess(a,b){showError("tmp",b);$I("errorMsg").innerHTML=a;$I("errorMsg").className="success-message"}
var navElem=$I("navigatie"),groupElem=$I("groepen"),stafElem=$I("staf"),actiElem=$I("activiteiten"),contElem=$I("contact"),huurElem=$I("verhuur"),scrollYpos=window.scrollY,scrolling=!1,menu=$I("menu-links"),menuClick=!1;window.onscroll=function(){scrollYpos=window.scrollY;requestScroll()};menu.onclick=function(a){var b=a.target.getAttribute("data-link");b&&(menuClick=!0,removeClass("menu-active"),a.target.classList.add("menu-active"),scrollUp(b))};
$I("contact-form").onsubmit=function(){for(var a={},b=/[^\s@]+@[^\s@]+\.[^\s@]+/,c=this.id,f=this.getElementsByClassName("inp"),e=0;e<f.length;e++)a[f[e].name]=f[e].value;a.whoTo||showError("Aan wie moet je vraag/opmerking verstuurd worden?",c);b.test(a.mailadr)||showError("Vul een geldig email adres in.",c);b.test(a.mailadr)&&""!==a.whoTo&&(removeError(),showSuccess("Aanmelding verstsuren...",c),ajax.post("../php/contact-form.php",a,function(a){$I(c).reset();showSuccess(a,c)}));return!1};
$I("hb-menu-btn-click").onclick=function(){$I("menu-links").classList.toggle("hb-menu-open");this.classList.toggle("hb-menu-btn-open")};var hired=[],isBetweenDate=function(a,b,c){var f,e;if(a){for(var d=0;d<a.length;d++)f=Date.parse(a[d].dayFrom),e=Date.parse(a[d].dayTo),b<=e&&b>=f&&c(a[d].bySV?"sv":"other");c(!1)}};(function(){var a=new Date;ajax.get("../php/Reservering.php",{m:a.getMonth()+1,y:a.getFullYear()},function(a){console.info(JSON.parse(a));processHired(JSON.parse(a))})})();
function processHired(a){var b=$I("mini-verhuur"),c=document.createDocumentFragment(),f,e,d,g,h,k,l=function(a){a=new Date(a);return"Zo Ma Di Wo Do Vr Za".split(" ")[a.getDay()]+" "+a.getDate()+" "+"Jan Feb Mrt Apr Mei Jun Jul Aug Sep Okt Nov Dec".split(" ")[a.getMonth()]+", "+a.getHours()+":00"},m=new Date;d=$el("ul");d.classList.add("hide-mobile");for(f=a.length-1;0<=f;f--)console.info(f),g=$el("li"),h=l(a[f].dayFrom),k=l(a[f].dayTo),g.innerHTML="Van: "+h+" tot: "+k,d.appendChild(g);c.appendChild(d);
e=$el("p");e.classList.add("verhuur-status");c.appendChild(e);isBetweenDate(a,m,function(a){e.innerHTML=a?"sv"===a?"De blokhut wordt gebruikt door Scouting Veghel.":"De blokhut is op dit moment bezet.":"De blokhut is op dit moment vrij."});b.innerHTML="";b.appendChild(c)};
