'use strict';var VERHUUR,ajax,navElem=$id("navigatie"),groupElem=$id("groepen"),actiElem=$id("activiteiten"),stafElem=$id("staf"),contElem=$id("contact"),huurElem=$id("verhuur"),scrollYpos=window.scrollY,isScrolling=!1,menu=$id("menu-links"),menuClick=!1,isTodayHired,setScroll;function $id(a){return document.getElementById(a)}function $elem(a){return document.createElement(a)}
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();function removeClass(a){var d=document.getElementsByClassName(a),b;for(b=0;b<d.length;b++)d[b].classList.remove(a)}
ajax=function(a,d,b){var e={},c=[];if("undefined"!==typeof XMLHttpRequest){var e=new XMLHttpRequest,f;for(f in d)c.push(encodeURIComponent(f)+"="+encodeURIComponent(d[f]));e.open("POST",a,!0);e.onreadystatechange=function(){4===e.readyState&&200===e.status?b(null,e.responseText):4===e.readyState&&200!==e.status&&b(!0)};e.onerror=function(){b(!0)};e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.send(c.join("&"))}else showError("Dingen zijn niet ondersteund... update je browser...")};
function getSetScrollFunction(){if(window.scrollTo)return function(a){window.scrollTo(0,a)};if(window.pageYOffset)return function(a){window.pageYOffset=a};if(document.documentElement.scrollTop)return function(){document.documentElement.scrollTop=to};if(document.body.scrollTop)return function(a){document.body.scrollTop=a}}setScroll=getSetScrollFunction();
function onScrollEvt(){var a=navElem.getBoundingClientRect(),d=groupElem.getBoundingClientRect(),b,e,c,f;0>=a.top&&d.top<=a.height?navElem.classList.add("nav-sticky-top"):navElem.classList.remove("nav-sticky-top");menuClick||(b=stafElem.getBoundingClientRect(),e=actiElem.getBoundingClientRect(),c=contElem.getBoundingClientRect(),f=huurElem.getBoundingClientRect(),removeClass("menu-active"),a.height>=d.top&&a.height<d.bottom&&menu.children[0].classList.add("menu-active"),a.height>=e.top&&a.height<
e.bottom&&menu.children[1].classList.add("menu-active"),a.height>=b.top&&a.height<b.bottom&&menu.children[2].classList.add("menu-active"),a.height>=c.top&&a.height<c.bottom&&menu.children[3].classList.add("menu-active"),a.height>=f.top&&a.height<f.bottom&&menu.children[4].classList.add("menu-active"));isScrolling=!1}function requestScroll(){isScrolling||requestAnimFrame(onScrollEvt);isScrolling=!0}
function scrollUp(a){function d(){if(50>h){var a=h;e=-f[0]*(a/=50)*(a-2)+b;var a=e,c=f[1]-1,d=f[1]+1;f[2]?a=a>=c&&a<=d:(a*=-1,a=a>=d&&a<=c);a?(setScroll(f[1]),menuClick=!1):(requestAnimFrame(g),h++)}}a=$id(a).offsetTop;var b,e,c=$id("navigatie").clientHeight,f=[],h=0,g=function(){setScroll(e);d()};b=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop;b<a?(f[0]=a-c-b,f[1]=a-c,f[2]=!0):(f[0]=-1*(b-(a-c)),f[1]=-1*(a-c),f[2]=!1);d()}
function showError(a,d){var b="",b=$id("errorMsg")?$id("errorMsg"):document.createElement("div");b.className="error-message";b.id="errorMsg";b.innerHTML='<i class="fa fa-times-circle"></i> '+a;d?$id(d).appendChild(b):console.error(a)}function removeError(){var a=$id("errorMsg");a&&a.parentNode.removeChild(a)}function showSuccess(a,d){showError("tmp",d);$id("errorMsg").innerHTML=a;$id("errorMsg").className="success-message"}
function resizeMap(){if($id("map-size")){var a=$id("map-size").clientWidth;$id("kaartje").innerHTML='<img class="info-kaart" alt="Locatie blokhut Scouting Veghel" src="//maps.googleapis.com/maps/api/staticmap?center=Dorshout+29,Veghel,NL&zoom=14&size='+a+'x300&scale=2&markers=color:blue%7C51.626782,5.522947&maptype=terrain&key=AIzaSyCgVa8lEEM_4SaJqtlLgl8QtBytdSSrhlM&sensor=false" />'}}resizeMap();window.addEventListener("resize",resizeMap);window.onscroll=function(){scrollYpos=window.scrollY;requestScroll()};
$id("arrowDown").onclick=function(){menuClick=!0;removeClass("menu-active");$id("menu-links").children[0].classList.add("menu-active");scrollUp("groepen")};$id("sv-logo").onclick=function(){removeClass("menu-active");scrollUp("landing-page")};
menu.onclick=function(a){var d=a.target.getAttribute("data-link");d&&(menuClick=!0,removeClass("menu-active"),menu.classList.contains("hb-menu-open")&&(menu.classList.toggle("hb-menu-open"),$id("hb-menu-btn-click").classList.toggle("hb-menu-btn-open")),a.target.classList.add("menu-active"),scrollUp(d),location.hash=d)};
$id("contact-form").onsubmit=function(){for(var a={},d=/[^\s@]+@[^\s@]+\.[^\s@]+/,b=this.id,e=this.getElementsByClassName("inp"),c=0;c<e.length;c++)a[e[c].name]=e[c].value;a.whoTo||showError("Aan wie moet de vraag of opmerking verstuurd worden?",b);d.test(a.mailadr)||showError("Vul een geldig e-mailadres in.",b);d.test(a.mailadr)&&""!==a.whoTo&&(removeError(),showSuccess("Vraag of opmerking aan het versturen...",b),ajax("../php/contact-form.php",a,function(a,c){$id(b).reset();showSuccess(c,b)}));
return!1};
$id("verhuur-form").onsubmit=function(){for(var a={},d=/[^\s@]+@[^\s@]+\.[^\s@]+/,b=this.id,e=this.getElementsByClassName("inp"),c=0;c<e.length;c++)a[e[c].name]=e[c].value;""!==a.groepcode?""!==a.people&&""!==a.tArea&&(showSuccess("Aanvraag voor de optie versturen...",b),ajax("../php/verhuur-form.php",a,function(a,c){$id(b).reset();showSuccess(c,b)})):(a.name||showError("Waarvoor is deze optie op de blokhut?",b),a.contactpersoon||showError("Wie wil deze optie op de blokhut nemen?",b),d.test(a.mailadr)||showError("Vul een geldig e-mailadres in.",
b),d.test(a.mailadr)&&""!==a.name&&""!==a.contactpersoon&&(removeError(),showSuccess("Aanvraag voor de optie versturen...",b),ajax("../php/verhuur-form.php",a,function(a,c){$id(b).reset();showSuccess(c,b)})));return!1};$id("verhuur-tabs").addEventListener("click",function(a){removeClass("tab-active");removeClass("tabpanel-active");a.target.classList.add("tab-active");$id(a.target.getAttribute("data-tab")).classList.add("tabpanel-active");"verhuur-stap-2"===a.target.getAttribute("data-tab")&&VERHUUR.setEindDays()});
$id("verhuur-goto-2").addEventListener("click",function(a){a.preventDefault();removeClass("tab-active");removeClass("tabpanel-active");$id("verhuur-stap-2").classList.add("tabpanel-active");$id("verhuur-tabs").children[1].classList.add("tab-active");VERHUUR.setEindDays()});$id("verhuur-goto-3").addEventListener("click",function(a){a.preventDefault();removeClass("tab-active");removeClass("tabpanel-active");$id("verhuur-stap-3").classList.add("tabpanel-active");$id("verhuur-tabs").children[2].classList.add("tab-active")});
$id("hb-menu-btn-click").onclick=function(){$id("menu-links").classList.toggle("hb-menu-open");this.classList.toggle("hb-menu-btn-open")};$id("groepcode").oninput=function(){var a=document.getElementsByClassName("verhuur-groepcode"),d=!0;""!==this.value&&(d=!1);for(var b=0;b<a.length;b++)a[b].required=d,a[b].disabled=!d};function checkMinMax(a,d){var b=a.getAttribute("min"),e=a.getAttribute("max");return b<d&&e>d?d:b>=d&&e>d?b:b<d&&e<=d?e:!1}
function verhuurDateTime(){function a(a){"number"===typeof a&&(a=checkMinMax(this,+this.value+a),!1!==a&&(this.value=a))}function d(a){"number"===typeof a&&(this.selectedIndex+=a,-1===this.selectedIndex&&(this.selectedIndex=0))}function b(){h[this.getAttribute("for")].onchange(this.getAttribute("data-plus-it")?1:-1)}function e(a){return 1===a.toString().length?"0"+a:a}var c={j:$id("aankomst-jaar"),m:$id("aankomst-maand"),d:$id("aankomst-dag"),uu:$id("aankomst-uur"),mm:$id("aankomst-minuut")},f={j:$id("vertrek-jaar"),
m:$id("vertrek-maand"),d:$id("vertrek-dag"),uu:$id("vertrek-uur"),mm:$id("vertrek-minuut")},h={"aankomst-jaar":c.j,"aankomst-maand":c.m,"aankomst-dag":c.d,"aankomst-uur":c.uu,"aankomst-minuut":c.mm,"vertrek-jaar":f.j,"vertrek-maand":f.m,"vertrek-dag":f.d,"vertrek-uur":f.uu,"vertrek-minuut":f.mm},g=document.getElementsByClassName("verhuur-label"),l=$id("EllenIkWil1DagHuren"),k;l.onchange=function(){var a,b,d;for(d in f)a=f[d],b=c[d],this.checked&&("SELECT"===a.nodeName?a.selectedIndex=b.selectedIndex:
a.value="uu"===d||"mm"===d?"uu"===d?23:59:b.value),a.required=!l.checked,a.disabled=l.checked};for(k=0;k<g.length;k++)g[k].addEventListener("click",b);c.m.onchange=d;f.m.onchange=d;c.d.onchange=a;c.j.onchange=a;c.uu.onchange=a;c.mm.onchange=a;f.d.onchange=a;f.j.onchange=a;f.uu.onchange=a;f.mm.onchange=a;g=new Date;k=new Date;k.setDate(k.getDate()+5);c.m.selectedIndex=g.getMonth();f.m.selectedIndex=k.getMonth();c.d.value=g.getDate();f.d.value=k.getDate();c.j.value=g.getFullYear();f.j.value=k.getFullYear();
c.uu.value=f.uu.value=g.getHours();c.mm.value=f.mm.value=g.getMinutes();return{setEindDays:function(){var a=c.j.value+"-"+e(c.m.selectedIndex+1)+"-"+e(c.d.value)+"T12:00",a=new Date(a);l.checked?(f.uu.value=23,f.mm.value=59):(a.setDate(a.getDate()+5),f.uu.value=12>c.uu.value?c.uu.value+8:c.uu.value,f.mm.value=c.mm.value);f.j.value=a.getFullYear();f.m.selectedIndex=a.getMonth();f.d.value=a.getDate()}}}VERHUUR=verhuurDateTime();
isTodayHired=function(a){var d,b,e=Date.now();if(a){for(var c=0;c<a.length;c++)if(d=Date.parse(a[c].dayFrom),b=Date.parse(a[c].dayTo),b=b===d?b+86399999:b,e<=b&&e>=d)return a[c].bySV?"sv":"other";return!1}};
(function(){var a=new Date;ajax("../php/Reservering.php",{d:a.getDate(),m:a.getMonth()+1,y:a.getFullYear()},function(a,b){var e=a;if(!a)try{processHired(JSON.parse(b))}catch(c){console.warn("Er is iets mis gegaan met het ophalen van de reserveringen.",b),e=!0}e&&($id("mini-verhuur").innerHTML='<p class="verhuur-status">Er is iets mis gegaan met het ophalen van de reserveringen.</p>')})})();(function(){var a=location.hash.replace("#",""),d;""!==a&&(d=$id(a))&&scrollUp(a)})();
function processHired(a){var d=$id("mini-verhuur"),b=document.createDocumentFragment(),e,c,f,h,g,l=function(a){a=new Date(a);return"zo ma di wo do vr za".split(" ")[a.getDay()]+". "+a.getDate()+" "+"jan feb mrt apr mei jun jul aug sep okt nov dec".split(" ")[a.getMonth()]+"."};c=$elem("ul");c.classList.add("hide-mobile");for(e=0;e<a.length;e++)f=$elem("li"),h=l(a[e].dayFrom),g=l(a[e].dayTo),f.textContent=g===h?"Op "+h:"Van "+h+" tot "+g,c.appendChild(f);b.appendChild(c);e=$elem("p");e.classList.add("verhuur-status");
b.appendChild(e);a=isTodayHired(a);e.textContent=a?"sv"===a?"De blokhut wordt gebruikt door Scouting Veghel.":"De blokhut is op dit moment bezet.":"De blokhut is op dit moment vrij.";d.innerHTML="";d.appendChild(b)};
